version: '3.8'

services:
    user:
        build:
            context: ./message-backend/user
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - user-db

    user-db:
        build:
            context: ./databases/user
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: user_db

    message:
        build:
            context: ./message-backend/message
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        depends_on:
            - message-db

    message-db:
        build:
            context: ./databases/message
            dockerfile: Dockerfile
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: message_db