apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: message-db
  name: message-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: message-db
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o k8s/
        kompose.version: 1.35.0 (9532ceef3)
      labels:
        io.kompose.service: message-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: message_db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: message-db
          name: message-db
          ports:
            - containerPort: 5432
              protocol: TCP
      restartPolicy: Always
